# Generated by Django 5.2.1 on 2025-07-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ragchunk',
            new_name='rag_chunks_user_id_aaf095_idx',
            old_name='rag_chunks_user_id_chunk_type_idx',
        ),
        migrations.RenameIndex(
            model_name='ragchunk',
            new_name='rag_chunks_user_id_20d71b_idx',
            old_name='rag_chunks_user_id_source_idx',
        ),
        migrations.RenameIndex(
            model_name='ragchunk',
            new_name='rag_chunks_updated_70d7de_idx',
            old_name='rag_chunks_updated_at_idx',
        ),
    ]
