# Generated by Django 5.2.1 on 2025-06-05 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('essay_type', models.CharField(choices=[('personal_statement', 'personal statement'), ('supplemental', 'supplemental essay'), ('scholarship', 'scholarship essay'), ('other', 'other')], default='personal_statement', max_length=20)),
                ('content', models.TextField()),
                ('prompt', models.TextField(blank=True, help_text='the essay prompt or question')),
                ('word_count', models.IntegerField(default=0)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_feedback', models.JSONField(blank=True, default=dict)),
                ('target_universities', models.ManyToManyField(blank=True, to='universities.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
