"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

import redis
from decouple import config

# build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# quick-start development settings - unsuitable for production
# see https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# security warning: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# security warning: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)
DOCKER = config("DOCKER", default=False, cast=bool)

# environment detection
LOCALDEV = DEBUG and not DOCKER
DOCKER_COMPOSE = DOCKER and DEBUG
PRODUCTION = not DEBUG

if LOCALDEV or DOCKER_COMPOSE:
    # local development or docker compose
    FRONTEND_URL = "http://localhost:3000"
    API_BASE_URL = "http://localhost:8000/api"
    print(f"🏠 local environment - frontend: {FRONTEND_URL}, api: {API_BASE_URL}")
else:
    # production deployment
    FRONTEND_URL = config("FRONTEND_URL", default="https://website-7lwhrqdbz-stdmity-aps-projects.vercel.app")
    API_BASE_URL = config("API_BASE_URL", default="https://your-api-domain.com/api")  # update this
    print(f"🌐 production environment - frontend: {FRONTEND_URL}, api: {API_BASE_URL}")

# ------------------------------------------
# allowed hosts & cors
# ------------------------------------------
if LOCALDEV or DOCKER_COMPOSE:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]
else:
    # production allowed hosts - add your actual domains here
    ALLOWED_HOSTS = [
        "your-api-domain.com",  # replace with your actual api domain
        "website-7lwhrqdbz-stdmity-aps-projects.vercel.app",
    ]

# cors configuration
CORS_ALLOWED_ORIGINS = [
    FRONTEND_URL,  # always include the current frontend url
]

# add localhost for development
if DEBUG:
    CORS_ALLOWED_ORIGINS.extend([
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ])

# only allow all origins in development
CORS_ALLOW_ALL_ORIGINS = DEBUG

# ------------------------------------------
# database configuration
# ------------------------------------------
DATABASE_URL = config("DATABASE_URL", default="")

if DATABASE_URL:
    # use provided database url (production)
    from dj_database_url import parse as dburl
    DATABASES = {"default": dburl(DATABASE_URL, conn_max_age=600)}
    print(f"✅ using configured database")
else:
    # fallback to sqlite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    print("⚠️ using sqlite fallback database")

# openai configuration (optional - required for AI features)
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')

# application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'storages', # for AWS S3

    # local apps
    'core',
    'users',
    'universities',
    'documents',
    'essays',
    'messaging',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # needs to be at the top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# caching configuration for embeddings
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'embedding-cache',
        'TIMEOUT': 60 * 60 * 24,  # 24 hours default
        'OPTIONS': {
            'MAX_ENTRIES': 10000,  # store up to 10k embeddings
            'CULL_FREQUENCY': 3,   # remove 1/3 when max reached
        }
    }
}

# password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ==========================================
# AWS S3 CONFIGURATION
# ==========================================

# aws credentials - will be loaded from .env file
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='college-app-demo')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')

# s3 storage settings
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',  # 24 hours
}
AWS_DEFAULT_ACL = 'private'  # keep all files private by default
AWS_S3_FILE_OVERWRITE = False  # don't overwrite files with same name
AWS_S3_CUSTOM_DOMAIN = None  # don't use cloudfront for now

# use s3 storage in production, local storage in development
USE_S3_STORAGE = config('USE_S3_STORAGE', default=False, cast=bool)

if USE_S3_STORAGE:
    # check if credentials are available
    if not AWS_ACCESS_KEY_ID or not AWS_SECRET_ACCESS_KEY:
        raise Exception("s3 storage is enabled but aws credentials are missing! check your .env file")

    # django 4.2+ storages setting for s3
    STORAGES = {
        "default": {
            "BACKEND": "config.s3_storage.SecureS3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    # for backwards compatibility with older django versions
    DEFAULT_FILE_STORAGE = 'config.s3_storage.SecureS3Storage'

    print("✅ s3 storage enabled")
else:
    # local storage for development
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    # local media settings
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    print("⚠️ using local storage")

# s3 specific security settings
S3_UPLOAD_EXPIRE_TIME = 900  # pre-signed urls expire in 15 minutes
S3_DOWNLOAD_EXPIRE_TIME = 900  # download urls expire in 15 minutes

# static files (css, javascript, images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ==========================================
# RAG AND EMBEDDING CONFIGURATION
# ==========================================

# embedding service settings
EMBEDDING_MODEL = "text-embedding-3-small"
EMBEDDING_DIMENSIONS = 1536
EMBEDDING_CACHE_TIMEOUT = 60 * 60 * 24  # 24 hours
EMBEDDING_MAX_BATCH_SIZE = 100

# rag system settings
RAG_MAX_CONTEXT_LENGTH = 3000  # max characters in context
RAG_DEFAULT_TOP_K = 5  # default number of chunks to retrieve
RAG_MIN_SIMILARITY_THRESHOLD = 0.3  # minimum similarity for relevance

# ai service settings
AI_MODEL = "gpt-4o"
AI_MAX_TOKENS = 1000
AI_TEMPERATURE = 0.7
AI_MAX_CONTEXT_MESSAGES = 8  # max conversation history messages

# default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django rest framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'upload_post_only': '10/hour',
        'user': '60/minute',
        'embedding': '100/hour',
        'rag': '200/hour'
    }
}

# JWT settings for authentication
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# cors headers that the frontend can use
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# file upload restrictions
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024 # 5MB soft cap
DATA_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024 # 30MB hard cap
DATA_UPLOAD_MAX_NUMBER_FIELDS = 500

# custom file upload settings
MAX_UPLOAD_SIZE = 25 * 1024 * 1024 # 25MB max file size

# allowed file extensions and mime types
ALLOWED_DOCUMENT_EXTENSIONS = [
    '.pdf', '.doc', '.docx', '.txt', '.rtf',
    '.jpg', '.jpeg', '.png', '.gif', '.bmp',
    '.tiff', '.tif'
]

ALLOWED_DOCUMENT_MIMETYPES = [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'text/plain',
    'text/rtf',
    'application/rtf',
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/bmp',
    'image/tiff',
]

# security settings
SECURE_FILE_UPLOADS = True
ENABLE_VIRUS_SCANNING = config('ENABLE_VIRUS_SCANNING', default=False, cast=bool)
ENABLE_CONTENT_ANALYSIS = config('ENABLE_CONTENT_ANALYSIS', default=False, cast=bool)

# ==========================================
# REDIS AND CELERY CONFIGURATION
# ==========================================

# redis configuration
if LOCALDEV:
    # local development - connect to localhost redis
    REDIS_HOST = 'localhost'
else:
    # docker/production - use service name or provided host
    REDIS_HOST = config("REDIS_HOST", default="redis")

REDIS_PORT = config("REDIS_PORT", cast=int, default=6379)
REDIS_DB = config("REDIS_DB", cast=int, default=0)
REDIS_PASSWORD = config('REDIS_PASSWORD', default=None)

# build redis url
if REDIS_PASSWORD:
    REDIS_URL = f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'
else:
    REDIS_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'

# test redis connection and configure celery
try:
    # test redis connection
    redis_client = redis.Redis.from_url(REDIS_URL)
    redis_client.ping()
    print("✅ redis connection successful")

    # celery configuration with redis
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_BROKER_TRANSPORT = 'redis'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_TIMEZONE = 'UTC'
    CELERY_ENABLE_UTC = True

    # task result expiration
    CELERY_RESULT_EXPIRES = 3600  # 1 hour

    # task routing for different queues
    CELERY_TASK_ROUTES = {
        'core.tasks.ocr_tasks.*': {'queue': 'ocr'},
        'core.tasks.embedding_tasks.*': {'queue': 'embedding'},
        'core.tasks.validation_tasks.*': {'queue': 'validation'},
        'core.tasks.*': {'queue': 'default'},
    }

    # worker settings
    CELERY_WORKER_PREFETCH_MULTIPLIER = 1
    CELERY_TASK_ACKS_LATE = True
    CELERY_TASK_REJECT_ON_WORKER_LOST = True

    # task execution mode
    USE_ASYNC_TASKS = config('USE_ASYNC_TASKS', default=True, cast=bool)

    if USE_ASYNC_TASKS:
        CELERY_TASK_ALWAYS_EAGER = False
        print("📝 async tasks enabled")
    else:
        CELERY_TASK_ALWAYS_EAGER = False
        print("📝 async tasks disabled - running synchronously")

    CELERY_AVAILABLE = True

except (redis.ConnectionError, redis.TimeoutError, Exception) as e:
    print(f"⚠️ redis connection failed: {e}")
    print("⚠️ celery tasks will run synchronously")

    # fallback configuration
    CELERY_TASK_ALWAYS_EAGER = False
    CELERY_TASK_EAGER_PROPAGATES = True
    CELERY_BROKER_URL = 'memory://'
    CELERY_RESULT_BACKEND = 'cache+memory://'
    CELERY_AVAILABLE = False
    USE_ASYNC_TASKS = False

# task timeout and retry settings
CELERY_TASK_SOFT_TIME_LIMIT = 300  # 5 minutes soft limit
CELERY_TASK_TIME_LIMIT = 600  # 10 minutes hard limit
CELERY_TASK_DEFAULT_RETRY_DELAY = 60  # 1 minute
CELERY_TASK_MAX_RETRIES = 3

# QDRANT

QDRANT_URL = config('QDRANT_URL', default='localhost')


# ==========================================
# LOGGING CONFIGURATION
# ==========================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '{asctime} - {name} - {levelname} - {funcName}:{lineno} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django.log',
            'formatter': 'verbose'
        },
        'embedding_debug': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'embedding_debug.log',
            'formatter': 'detailed'
        },
        'celery_debug': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'celery_debug.log',
            'formatter': 'detailed'
        },
    },
    'root': {
        'level': 'INFO',
        'handlers': ['console'],
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'celery': {
            'handlers': ['console', 'celery_debug'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'celery.task': {
            'handlers': ['console', 'celery_debug'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'core.tasks.embedding_tasks': {
            'handlers': ['console', 'file', 'embedding_debug'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'core.services.embedding_service': {
            'handlers': ['console', 'file', 'embedding_debug'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'core.services.ai_service': {
            'handlers': ['console', 'file', 'embedding_debug'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'documents.tasks.ocr_tasks': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'core.services.ocr_service': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'users.views': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'users.base_views': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'api.s3_operations': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'messaging.rag_service': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'qdrant_client': {
            'handlers': ['console', 'embedding_debug'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'openai': {
            'handlers': ['console', 'embedding_debug'],
            'level': 'INFO',
            'propagate': False,
        },
        'httpx': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}