# Generated by Django 5.2.1 on 2025-06-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='high_school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
