# Generated by Django 5.2.1 on 2025-06-10 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_academicinfo_graduation_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='gpa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
    ]
