# Generated by Django 5.2.1 on 2025-06-05 17:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('admission_chance', models.FloatField(help_text='admission chance as percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('acceptance_rate', models.FloatField(help_text='acceptance rate as percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('avg_sat_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(1600)])),
                ('avg_gpa', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('annual_tuition', models.IntegerField(help_text='annual tuition in USD')),
                ('has_financial_aid', models.BooleanField(default=True)),
                ('website_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('ranking', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'universities',
                'ordering': ['ranking', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_universities', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='universities.university')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'university')},
            },
        ),
    ]
