# Generated by Django 5.2.1 on 2025-06-16 18:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGChunk',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('chunk_type', models.CharField(choices=[('profile', 'Profile'), ('document', 'Document')], max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=1536)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_chunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rag_chunks',
                'indexes': [models.Index(fields=['user', 'chunk_type'], name='rag_chunks_user_id_aaf095_idx'), models.Index(fields=['user', 'source'], name='rag_chunks_user_id_20d71b_idx'), models.Index(fields=['updated_at'], name='rag_chunks_updated_70d7de_idx')],
            },
        ),
    ]
