# Generated by Django 5.2.1 on 2025-06-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_metadata_alter_message_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragchunk',
            name='embedding',
            field=models.TextField(),
        ),
    ]
