# Generated by Django 5.2.1 on 2025-06-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_alter_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ragchunk',
            name='embedding',
        ),
        migrations.AddField(
            model_name='ragchunk',
            name='embedding_data',
            field=models.TextField(blank=True, help_text='json encoded embedding vector', null=True),
        ),
    ]
