# Generated by Django 5.2.1 on 2025-06-18 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_remove_ragchunk_embedding_ragchunk_embedding_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ragchunk',
            name='embedding_data',
        ),
    ]
