# Generated by Django 5.2.1 on 2025-06-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_remove_ragchunk_embedding_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragchunk',
            name='embedding',
            field=models.JSONField(blank=True, default=list, help_text='embedding vector as json array'),
        ),
    ]
