# Generated by Django 5.2.1 on 2025-06-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_ragchunk_embedding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RAGChunk',
        ),
    ]
