# Generated by Django 5.2.1 on 2025-06-05 17:56

from core.validators.document_validators import *
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('transcript', 'high school transcript'), ('sat_score', 'sat score report'), ('act_score', 'act score report'), ('toefl_score', 'toefl score report'), ('ielts_score', 'ielts score report'), ('recommendation', 'letter of recommendation'), ('other', 'other')], max_length=20)),
                ('s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('original_filename', models.CharField(default='unknown_file.pdf', max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', validators=[validate_document_file])),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('error', 'error')], default='pending', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
