# Generated by Django 5.2.1 on 2025-06-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Text extracted from document via OCR', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_error',
            field=models.TextField(blank=True, help_text='Error message if OCR processing failed', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata from OCR processing (page count, method, etc.)'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('failed', 'failed')], default='pending', help_text='Status of OCR text extraction', max_length=20, null=True),
        ),
    ]
