# Generated by Django 5.2.1 on 2025-07-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_extracted_text_document_ocr_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='validation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='validation_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='validation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='validation_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('transcript', 'high school transcript'), ('sat_score', 'sat score report'), ('act_score', 'act score report'), ('toefl_score', 'toefl score report'), ('ielts_score', 'ielts score report'), ('recommendation', 'letter of recommendation'), ('personal_statement', 'personal statement'), ('bank_statement', 'bank statement'), ('i20', 'i-20 form'), ('passport', 'passport copy'), ('visa', 'visa document'), ('other', 'other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('completed', 'completed'), ('validated', 'validated'), ('validation_failed', 'validation_failed'), ('validation_error', 'validation_error'), ('error', 'error')], default='pending', max_length=20),
        ),
    ]
