# Generated by Django 5.2.1 on 2025-07-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('validation_failed', 'Validation Failed'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
